# -*- coding: utf-8 -*-
"""Aula 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYDN4Y71r45mn3PFf0wVfF6DC6VIGRNI
"""

# Atividade 1

resp = input("Saudações a você: ").lower()

if(resp =="olá" or resp =="ola" or resp =="oi"):
  print("Olá")
elif( resp == "tchau"):
  print("Até logo!")
else:
  print("Não entendi sua mensagem!")

# Atividade 2

resp = input("Qual é o Problema? ").lower()
problema = ["internet","computador"]

if problema[0] in resp:
  print("Problema de rede")
elif problema[1] in resp:
  print("Problema de hardware")
else:
    print("Problema desconhecido")

# Atividade 3

idade = int(input("Digite sua idade: "))

if 12 > idade:
  print("Criança")
if 12 <= idade and 17 > idade:
  print("Adolescente")
if 18 <= idade and 64 > idade:
  print("Adulto")
if idade > 64:
  print("Idoso")

# Atividade  4

from datetime import datetime

hora = datetime.now().hour

if 8 >= hora and hora >= 18 :
  print("Estama Funcionando!")
else:
  print("Desculpa,mas nesse horario estamos fechado,volte entre 8 ás 18 horas")
  exit()

nome = input("Qual é o seu nome? ")
idade = input("Qual sua idade? ")
print(f"Seu nome é {nome}! e sua idade é {idade}!")

# Atividade 5 (rever se esta correto)

usuarios_logados = ["peter", "gabriel", "pedro"]
administradores = ["pedro_fluminense", "david.c"]

nome = input("Digite seu nome: ").lower()

if nome in usuarios_logados and nome in administradores:
    print("Acesso total")
elif nome in usuarios_logados:
    print("Acesso restrito")
else:
    print("Acesso negado")

# Atividade 6

temp = float(input("Qual é a sua temperatura? "))

if temp >= 39:
  print("Febre Alta")
elif temp <= 38.9 and temp >= 37.5:
  print("febre")
else :
  print("Temperatura Normal")

# Atividade 7 (Rever se esta correto)

intencao = input("Digite sua intenção (saudacao, ajuda ou reclamacao): ")

if intencao == "saudacao":
    print("Olá! Seja bem-vindo!")
elif intencao == "ajuda":
    print("Claro! Como posso ajudar?")
elif intencao == "reclamacao":
    print("Sinto muito pelo ocorrido. Como podemos resolver?")
else:
    print("Intenção não reconhecida.")

# Atividade 8

valor = int(input("Qual é o valor que vc esta disposto a pagar  por mes? "))

if valor > 0:
  print("Valor Aceito")
else:
  print("Erro no valor escolhido")

# Atividade 9

mensagem = input("Digite sua mensagem: ")
idioma = input("Digite o idioma (pt, en, es): ")

if idioma == "pt":
    print("Olá! Como posso ajudar?")
elif idioma == "en":
    print("Hello! How can I help you?")
elif idioma == "es":
    print("¡Hola! ¿Cómo puedo ayudarte?")
else:
    print("Idioma não reconhecido.")

# Atividade 10

mensagem = input("Digite sua mensagem: ")

if mensagem == "sair" or mensagem == "exit":
    print("Encerrando conversa...")
else:
    print("Como posso ajudar?")